### PR TITLE
Unique Container Storage Identification required for Libcstor

### PR DESCRIPTION
**Pull request by Apollo9999**
PR raised by skjkiran0212@gmail.com

### CODE REVIEW

**Comment by pawanpraka1** [comment]
can you raise the PR in master branch instread of raising it to the v1.0.x branch.

**Comment by Apollo9999** [comment]
Pawan I raised PR in the master.Kindly make the necessary changes

**Comment by pawanpraka1** [comment]
see the top line of this PR which says "Apollo9999 wants to merge 16 commits into openebs:v1.0.x from Apollo9999:master". You have raised the PR from your master to v1.0.x branch. Also can you please explain what is the purpose of this PR as the PR description is saying "Unique Container Storage Identification required for Libcstor " but I don't see any change related to that.

**Comment by vishnuitta** [comment]
I'm seeing another PR of the same to master branch.. hence closing this

**Pull request closed without merging**
